# Build Stage
FROM node:20 AS builder
WORKDIR /app
COPY package*.json .
RUN yarn install
COPY . .

ENV REACT_APP_URL_API=http://localhost:8000
ENV DEPLOY=PROD
RUN yarn run build


# Production Stage
# FROM nginx:alpine as prod
# COPY --from=builder /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf
# WORKDIR /usr/share/nginx/html
# RUN rm -rf ./*
# COPY --from=builder /app/dist .
# CMD ["nginx", "-g", "daemon off;"]